ex_compile: ex_compile.c
	gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include ex_compile.c -o ex_compile -lglib-2.0

word_count: word_count.c
	gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include word_count.c -o word_count -lglib-2.0